#!/usr/bin/env python3
"""Generate immutable deployment metadata from a certified image manifest.

The manifest is the only source of image repository names, exact multi-arch
index digests, release Git commit, and Alembic head. Operators cannot rebuild
those values from a convenient mutable repository/tag argument.

Usage:
  scripts/prod/write-release-env.py <version>
      [--manifest production/image-manifest.json] [--force]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
IMAGE_RE = re.compile(r"^[a-z0-9][a-z0-9._/-]*(?::[A-Za-z0-9._-]+)?$")
SHA_RE = re.compile(r"^[0-9a-f]{40}(?:[0-9a-f]{24})?$")
IDENTIFIER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
SCHEMA_VERSION = 2
SERVICES = {"backend": "CYGNUS_API_IMAGE", "frontend": "CYGNUS_FRONTEND_IMAGE"}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _released_ref(entry: object, name: str) -> str:
    if not isinstance(entry, dict):
        raise ValueError(f"images.{name} must be an object")
    image = entry.get("image")
    digest = entry.get("digest")
    if entry.get("status") != "released":
        raise ValueError(f"images.{name}.status must be 'released'")
    if not isinstance(image, str) or not IMAGE_RE.fullmatch(image):
        raise ValueError(
            f"images.{name}.image is not a lowercase immutable registry name"
        )
    if not isinstance(digest, str) or not DIGEST_RE.fullmatch(digest):
        raise ValueError(f"images.{name}.digest is not sha256:<64 hex>")
    return f"{image}@{digest}"


def build_release_env(
    *, version: str, manifest: dict[str, object], manifest_path: Path
) -> str:
    if not IDENTIFIER_RE.fullmatch(version):
        raise ValueError("version must be a safe release identifier")
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ValueError(
            f"unsupported manifest schema_version: {manifest.get('schema_version')!r} (expected {SCHEMA_VERSION})"
        )
    git = manifest.get("git")
    if (
        not isinstance(git, dict)
        or not isinstance(git.get("sha"), str)
        or not SHA_RE.fullmatch(git["sha"])
    ):
        raise ValueError("manifest git.sha is not a commit SHA")
    head = manifest.get("alembic_head")
    if not isinstance(head, str) or not IDENTIFIER_RE.fullmatch(head):
        raise ValueError("manifest alembic_head is missing or unsafe")
    images = manifest.get("images")
    if not isinstance(images, dict):
        raise ValueError("manifest images must be an object")
    refs = {name: _released_ref(images.get(name), name) for name in SERVICES}
    lines = [
        "# Generated by scripts/prod/write-release-env.py; do not edit.",
        f"# source: {manifest_path} (schema_version {SCHEMA_VERSION})",
        f"# git {git['sha']} ref {git.get('ref', '?')} created {manifest.get('created', '')}",
        f"APP_RELEASE={version}",
        f"APP_COMMIT_SHA={git['sha']}",
        f"EXPECTED_ALEMBIC_HEAD={head}",
        f"CYGNUS_API_IMAGE={refs['backend']}",
        f"CYGNUS_FRONTEND_IMAGE={refs['frontend']}",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="approved release identifier, e.g. 0.1.0")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=repo_root() / "production" / "image-manifest.json",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace an existing metadata file after explicit operator review",
    )
    args = parser.parse_args(argv)
    try:
        manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
        if not isinstance(manifest, dict):
            raise ValueError("manifest must be a JSON object")
        content = build_release_env(
            version=args.version, manifest=manifest, manifest_path=args.manifest
        )
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        parser.error(str(exc))
    target = repo_root() / "deploy" / "releases" / f"{args.version}.env"
    if target.exists() and not args.force:
        parser.error(
            f"{target} already exists — immutable release metadata is not overwritten without --force"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
